services:
  elasticsearch:
    image: elasticsearch:8.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "TZ=Asia/Shanghai"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false # 禁用安全功能(仅用于开发环境)
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${PWD}/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - develop

  kibana:
    image: kibana:8.17.9
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - I18N_LOCALE=zh-CN
      - "TZ=Asia/Shanghai"
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - develop
networks:
  develop:
    external: true