services:
  rabbitmq:
    image: rabbitmq:3.13.7-management    # 带管理插件版本
    container_name: rabbitmq
    hostname: rabbitmq                   # 重要：集群时需要唯一hostname
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=root       # 默认管理员用户名
      - RABBITMQ_DEFAULT_PASS=root       # 默认密码
      - RABBITMQ_DEFAULT_VHOST=/         # 默认虚拟主机
    volumes:
      - ${PWD}/conf:/etc/rabbitmq       # 配置文件
      - ${PWD}/data:/var/lib/rabbitmq   # 数据持久化
      - ${PWD}/log:/var/log/rabbitmq    # 日志持久化
    ports:
      - "5672:5672"   # AMQP协议端口
      - "15672:15672" # 管理界面端口
      - "25672:25672" # 集群通信端口
    networks:
      - develop
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  develop:
    external: true